# This file configures the hello-world app which serves public web traffic.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: controller-service-v1
# namespace: cepstralinstruments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller-service
  template:
    metadata:
      labels:
        app: controller-service
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: controller-service-account
      containers:
        - name: controller-service
          image: gcr.io/samplergan/controller-service:latest
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env:
            - name: RHOST
              value: 'rabbit-mq-service'
            - name: RUSER
              value: 'guest'
            - name: RPASS
              value: 'guest'
            - name: RVHOST
              value: '/'
            - name: TRAINER
              value: '153671080191723390'
            - name: ZONE
              value: 'us-west1-b'
            - name: PROJECT_ID
              value: 'samplergan'
            - name: PGHOST
              value: 'sqlproxy-service-database1'
            - name: PGDATABASE
              value: 'ml-pipe-database'
            - name: PGUSER
              value: 'villi'
            - name: PGPASSWORD
              value: 'aframgakk19'
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json