# This file configures the hello-world app which serves public web traffic.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingestion-service
# namespace: cepstralinstruments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-service
  template:
    metadata:
      labels:
        app: ingestion-service
    spec:
      containers:
        - name: ingestion-service
          image: gcr.io/samplergan/ingestion-service:latest
          env:
            - name: RABBIT
              value: '10.27.240.87'
            - name: RABBIT_USER
              value: 'admin'
            - name: RABBIT_PASS
              value: 'aframgakk19'