apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: main-ingress
spec:
  rules:
  - http:
      paths:
      - path: /admin/*
        backend:
          serviceName: training-scheduler-service
          servicePort: 5007
