apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq-service
spec:
  type: NodePort
  ports:
    - port: 5672
      name: rabbit-tcp
    - port: 15672
      targetPort: 15672
      name: rabbit-http
  selector:
    app: rabbit-mq
