# This file configures the hello-world app which serves public web traffic.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: training-scheduler
# namespace: cepstralinstruments
spec:
  replicas: 1
  selector:
    matchLabels:
      run: training-scheduler
  template:
    metadata:
      labels:
        run: training-scheduler
    spec:
      containers:
        - name: training-scheduler
          image: gcr.io/samplergan/training-scheduler:latest
          ports:
            - name: main
              protocol: TCP
              containerPort: 5007
          env:
            - name: RHOST
              value: 'rabbit-mq-service'
            - name: RUSER
              value: 'guest'
            - name: RPASS
              value: 'guest'
            - name: RVHOST
              value: '/'
            - name: TOKEN
              value: 'asghwegalkjerhghoaier0439845!'
            - name: PGHOST
              value: '34.89.28.185'
            - name: PGDATABASE
              value: 'ml-pipe-database'
            - name: PGUSER
              value: 'villi'
            - name: PGPASSWORD
              value: 'aframgakk19'
