apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: training-scheduler-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: training-scheduler
        version: v1
    spec:
      containers:
      - name: training-scheduler
        image: gcr.io/samplergan/training-scheduler:latest
        ports:
        - containerPort: 5007
        readinessProbe:
          httpGet:
            path: healthcheck
            port: 5007
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
          - name: RHOST
            value: 'rabbit-mq-service'
          - name: RUSER
            value: 'guest'
          - name: RPASS
            value: 'guest'
          - name: RVHOST
            value: '/'
          - name: TOKEN
            value: 'asghwegalkjerhghoaier0439845!'
          - name: PGHOST
            value: 'sqlproxy-service-database1'
          - name: PGDATABASE
            value: 'ml-pipe-database'
          - name: PGUSER
            value: 'villi'
          - name: PGPASSWORD
            value: 'aframgakk19'