kind: Service
apiVersion: v1
metadata:
  name: training-scheduler
  labels:
    run: training-scheduler
spec:
  type: NodePort
  selector:
    app: training-scheduler
  ports:
    - port: 5007
      protocol: TCP
