apiVersion: v1
kind: Service
metadata:
  name: training-scheduler-srv
  labels:
    app: training-scheduler
spec:
  type: NodePort
  ports:
  - port: 5007
    name: http
  selector:
    app: training-scheduler

