kind: Service
apiVersion: v1
metadata:
  name: training-scheduler
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: training-scheduler
  ports:
    - port: 5007
      targetPort: 5007
      protocol: TCP

