get_records = {
    'names': [
        'WRLD-Kick-1-D.wav',
        'WRLD-Kick-3-G.wav',
           'WRLD-Kick-5-A.wav',
           'WRLD-Kick-2-F.wav', 'WRLD-Kick-6-B.wav',
           'WRLD-Kick-4-G.wav', 'WRLDClosedHihat3.wav', 'WRLDClosedHihat2.wav', 'WRLDClosedHihat1.wav',
           'WRLDOpenHihat4.wav', 'WRLDClosedHihat 4.wav', 'WRLDOpenHihat1.wav', 'WRLDOpenHihat3.wav',
           'WRLDOpenHihat2.wav', 'WRLDSnare5-G#.wav', 'WRLDSnare2-C#.wav', 'WRLDSnare4-F.wav', 'WRLDSnare6-A.wav',
           'WRLDSnare1-C.wav', 'WRLDSnare3-D.wav', 'WRLDCrash1.wav', 'WRLDCrash2.wav', 'WRLDCrash3.wav',
           'WRLDPercussion7.wav', 'WRLDPercussion6.wav', 'WRLDPercussion4.wav', 'WRLDPercussion5.wav',
           'WRLDPercussion1.wav', 'WRLDPercussion2.wav', 'WRLDPercussion3.wav', 'WRLDClap4.wav', 'WRLDClap5.wav',
           'WRLDClap2.wav', 'WRLDClap3.wav', 'WRLDClap1.wav'], 'locations': [
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/KICK/WRLD-Kick-1-D.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/KICK/WRLD-Kick-3-G.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/KICK/WRLD-Kick-5-A.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/KICK/WRLD-Kick-2-F.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/KICK/WRLD-Kick-6-B.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/KICK/WRLD-Kick-4-G.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/HIHAT/WRLDClosedHihat3.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/HIHAT/WRLDClosedHihat2.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/HIHAT/WRLDClosedHihat1.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/HIHAT/WRLDOpenHihat4.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/HIHAT/WRLDClosedHihat 4.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/HIHAT/WRLDOpenHihat1.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/HIHAT/WRLDOpenHihat3.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/HIHAT/WRLDOpenHihat2.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/SNARE/WRLDSnare5-G#.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/SNARE/WRLDSnare2-C#.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/SNARE/WRLDSnare4-F.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/SNARE/WRLDSnare6-A.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/SNARE/WRLDSnare1-C.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/SNARE/WRLDSnare3-D.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/CRASH/WRLDCrash1.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/CRASH/WRLDCrash2.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/CRASH/WRLDCrash3.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/PERCUSSION/WRLDPercussion7.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/PERCUSSION/WRLDPercussion6.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/PERCUSSION/WRLDPercussion4.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/PERCUSSION/WRLDPercussion5.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/PERCUSSION/WRLDPercussion1.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/PERCUSSION/WRLDPercussion2.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/PERCUSSION/WRLDPercussion3.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/CLAP/WRLDClap4.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/CLAP/WRLDClap5.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/CLAP/WRLDClap2.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/CLAP/WRLDClap3.wav',
    '/Users/vilhjamurr.vilhjalmsson/Desktop/Projects/GAN_pipe/Data/wisebeat/raw_sound_repo/CLAP/WRLDClap1.wav'],
 'types': ['KICK', 'KICK', 'KICK', 'KICK', 'KICK', 'KICK', 'HIHAT', 'HIHAT', 'HIHAT', 'HIHAT', 'HIHAT', 'HIHAT',
           'HIHAT', 'HIHAT', 'SNARE', 'SNARE', 'SNARE', 'SNARE', 'SNARE', 'SNARE', 'CRASH', 'CRASH', 'CRASH',
           'PERCUSSION', 'PERCUSSION', 'PERCUSSION', 'PERCUSSION', 'PERCUSSION', 'PERCUSSION', 'PERCUSSION', 'CLAP',
           'CLAP', 'CLAP', 'CLAP', 'CLAP'
           ]
}
